
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Curriculum` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Curriculum
 * 
 */
export type CurriculumModel = runtime.Types.Result.DefaultSelection<Prisma.$CurriculumPayload>

export type AggregateCurriculum = {
  _count: CurriculumCountAggregateOutputType | null
  _avg: CurriculumAvgAggregateOutputType | null
  _sum: CurriculumSumAggregateOutputType | null
  _min: CurriculumMinAggregateOutputType | null
  _max: CurriculumMaxAggregateOutputType | null
}

export type CurriculumAvgAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type CurriculumSumAggregateOutputType = {
  id: number | null
  userId: number | null
}

export type CurriculumMinAggregateOutputType = {
  id: number | null
  userId: number | null
  url: string | null
  createdAt: Date | null
}

export type CurriculumMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  url: string | null
  createdAt: Date | null
}

export type CurriculumCountAggregateOutputType = {
  id: number
  userId: number
  url: number
  createdAt: number
  _all: number
}


export type CurriculumAvgAggregateInputType = {
  id?: true
  userId?: true
}

export type CurriculumSumAggregateInputType = {
  id?: true
  userId?: true
}

export type CurriculumMinAggregateInputType = {
  id?: true
  userId?: true
  url?: true
  createdAt?: true
}

export type CurriculumMaxAggregateInputType = {
  id?: true
  userId?: true
  url?: true
  createdAt?: true
}

export type CurriculumCountAggregateInputType = {
  id?: true
  userId?: true
  url?: true
  createdAt?: true
  _all?: true
}

export type CurriculumAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Curriculum to aggregate.
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Curricula to fetch.
   */
  orderBy?: Prisma.CurriculumOrderByWithRelationInput | Prisma.CurriculumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CurriculumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Curricula from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Curricula.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Curricula
  **/
  _count?: true | CurriculumCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CurriculumAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CurriculumSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CurriculumMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CurriculumMaxAggregateInputType
}

export type GetCurriculumAggregateType<T extends CurriculumAggregateArgs> = {
      [P in keyof T & keyof AggregateCurriculum]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCurriculum[P]>
    : Prisma.GetScalarType<T[P], AggregateCurriculum[P]>
}




export type CurriculumGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CurriculumWhereInput
  orderBy?: Prisma.CurriculumOrderByWithAggregationInput | Prisma.CurriculumOrderByWithAggregationInput[]
  by: Prisma.CurriculumScalarFieldEnum[] | Prisma.CurriculumScalarFieldEnum
  having?: Prisma.CurriculumScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CurriculumCountAggregateInputType | true
  _avg?: CurriculumAvgAggregateInputType
  _sum?: CurriculumSumAggregateInputType
  _min?: CurriculumMinAggregateInputType
  _max?: CurriculumMaxAggregateInputType
}

export type CurriculumGroupByOutputType = {
  id: number
  userId: number
  url: string
  createdAt: Date
  _count: CurriculumCountAggregateOutputType | null
  _avg: CurriculumAvgAggregateOutputType | null
  _sum: CurriculumSumAggregateOutputType | null
  _min: CurriculumMinAggregateOutputType | null
  _max: CurriculumMaxAggregateOutputType | null
}

type GetCurriculumGroupByPayload<T extends CurriculumGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CurriculumGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CurriculumGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CurriculumGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CurriculumGroupByOutputType[P]>
      }
    >
  >



export type CurriculumWhereInput = {
  AND?: Prisma.CurriculumWhereInput | Prisma.CurriculumWhereInput[]
  OR?: Prisma.CurriculumWhereInput[]
  NOT?: Prisma.CurriculumWhereInput | Prisma.CurriculumWhereInput[]
  id?: Prisma.IntFilter<"Curriculum"> | number
  userId?: Prisma.IntFilter<"Curriculum"> | number
  url?: Prisma.StringFilter<"Curriculum"> | string
  createdAt?: Prisma.DateTimeFilter<"Curriculum"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CurriculumOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type CurriculumWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CurriculumWhereInput | Prisma.CurriculumWhereInput[]
  OR?: Prisma.CurriculumWhereInput[]
  NOT?: Prisma.CurriculumWhereInput | Prisma.CurriculumWhereInput[]
  userId?: Prisma.IntFilter<"Curriculum"> | number
  url?: Prisma.StringFilter<"Curriculum"> | string
  createdAt?: Prisma.DateTimeFilter<"Curriculum"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type CurriculumOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CurriculumCountOrderByAggregateInput
  _avg?: Prisma.CurriculumAvgOrderByAggregateInput
  _max?: Prisma.CurriculumMaxOrderByAggregateInput
  _min?: Prisma.CurriculumMinOrderByAggregateInput
  _sum?: Prisma.CurriculumSumOrderByAggregateInput
}

export type CurriculumScalarWhereWithAggregatesInput = {
  AND?: Prisma.CurriculumScalarWhereWithAggregatesInput | Prisma.CurriculumScalarWhereWithAggregatesInput[]
  OR?: Prisma.CurriculumScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CurriculumScalarWhereWithAggregatesInput | Prisma.CurriculumScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Curriculum"> | number
  userId?: Prisma.IntWithAggregatesFilter<"Curriculum"> | number
  url?: Prisma.StringWithAggregatesFilter<"Curriculum"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Curriculum"> | Date | string
}

export type CurriculumCreateInput = {
  url: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCurriculumsInput
}

export type CurriculumUncheckedCreateInput = {
  id?: number
  userId: number
  url: string
  createdAt?: Date | string
}

export type CurriculumUpdateInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCurriculumsNestedInput
}

export type CurriculumUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CurriculumCreateManyInput = {
  id?: number
  userId: number
  url: string
  createdAt?: Date | string
}

export type CurriculumUpdateManyMutationInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CurriculumUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CurriculumListRelationFilter = {
  every?: Prisma.CurriculumWhereInput
  some?: Prisma.CurriculumWhereInput
  none?: Prisma.CurriculumWhereInput
}

export type CurriculumOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CurriculumCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CurriculumAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type CurriculumMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CurriculumMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CurriculumSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type CurriculumCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CurriculumCreateWithoutUserInput, Prisma.CurriculumUncheckedCreateWithoutUserInput> | Prisma.CurriculumCreateWithoutUserInput[] | Prisma.CurriculumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CurriculumCreateOrConnectWithoutUserInput | Prisma.CurriculumCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CurriculumCreateManyUserInputEnvelope
  connect?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
}

export type CurriculumUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CurriculumCreateWithoutUserInput, Prisma.CurriculumUncheckedCreateWithoutUserInput> | Prisma.CurriculumCreateWithoutUserInput[] | Prisma.CurriculumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CurriculumCreateOrConnectWithoutUserInput | Prisma.CurriculumCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CurriculumCreateManyUserInputEnvelope
  connect?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
}

export type CurriculumUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CurriculumCreateWithoutUserInput, Prisma.CurriculumUncheckedCreateWithoutUserInput> | Prisma.CurriculumCreateWithoutUserInput[] | Prisma.CurriculumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CurriculumCreateOrConnectWithoutUserInput | Prisma.CurriculumCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CurriculumUpsertWithWhereUniqueWithoutUserInput | Prisma.CurriculumUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CurriculumCreateManyUserInputEnvelope
  set?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  disconnect?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  delete?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  connect?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  update?: Prisma.CurriculumUpdateWithWhereUniqueWithoutUserInput | Prisma.CurriculumUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CurriculumUpdateManyWithWhereWithoutUserInput | Prisma.CurriculumUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CurriculumScalarWhereInput | Prisma.CurriculumScalarWhereInput[]
}

export type CurriculumUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CurriculumCreateWithoutUserInput, Prisma.CurriculumUncheckedCreateWithoutUserInput> | Prisma.CurriculumCreateWithoutUserInput[] | Prisma.CurriculumUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CurriculumCreateOrConnectWithoutUserInput | Prisma.CurriculumCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CurriculumUpsertWithWhereUniqueWithoutUserInput | Prisma.CurriculumUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CurriculumCreateManyUserInputEnvelope
  set?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  disconnect?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  delete?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  connect?: Prisma.CurriculumWhereUniqueInput | Prisma.CurriculumWhereUniqueInput[]
  update?: Prisma.CurriculumUpdateWithWhereUniqueWithoutUserInput | Prisma.CurriculumUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CurriculumUpdateManyWithWhereWithoutUserInput | Prisma.CurriculumUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CurriculumScalarWhereInput | Prisma.CurriculumScalarWhereInput[]
}

export type CurriculumCreateWithoutUserInput = {
  url: string
  createdAt?: Date | string
}

export type CurriculumUncheckedCreateWithoutUserInput = {
  id?: number
  url: string
  createdAt?: Date | string
}

export type CurriculumCreateOrConnectWithoutUserInput = {
  where: Prisma.CurriculumWhereUniqueInput
  create: Prisma.XOR<Prisma.CurriculumCreateWithoutUserInput, Prisma.CurriculumUncheckedCreateWithoutUserInput>
}

export type CurriculumCreateManyUserInputEnvelope = {
  data: Prisma.CurriculumCreateManyUserInput | Prisma.CurriculumCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CurriculumUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CurriculumWhereUniqueInput
  update: Prisma.XOR<Prisma.CurriculumUpdateWithoutUserInput, Prisma.CurriculumUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CurriculumCreateWithoutUserInput, Prisma.CurriculumUncheckedCreateWithoutUserInput>
}

export type CurriculumUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CurriculumWhereUniqueInput
  data: Prisma.XOR<Prisma.CurriculumUpdateWithoutUserInput, Prisma.CurriculumUncheckedUpdateWithoutUserInput>
}

export type CurriculumUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CurriculumScalarWhereInput
  data: Prisma.XOR<Prisma.CurriculumUpdateManyMutationInput, Prisma.CurriculumUncheckedUpdateManyWithoutUserInput>
}

export type CurriculumScalarWhereInput = {
  AND?: Prisma.CurriculumScalarWhereInput | Prisma.CurriculumScalarWhereInput[]
  OR?: Prisma.CurriculumScalarWhereInput[]
  NOT?: Prisma.CurriculumScalarWhereInput | Prisma.CurriculumScalarWhereInput[]
  id?: Prisma.IntFilter<"Curriculum"> | number
  userId?: Prisma.IntFilter<"Curriculum"> | number
  url?: Prisma.StringFilter<"Curriculum"> | string
  createdAt?: Prisma.DateTimeFilter<"Curriculum"> | Date | string
}

export type CurriculumCreateManyUserInput = {
  id?: number
  url: string
  createdAt?: Date | string
}

export type CurriculumUpdateWithoutUserInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CurriculumUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CurriculumUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CurriculumSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  url?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["curriculum"]>

export type CurriculumSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  url?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["curriculum"]>

export type CurriculumSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  url?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["curriculum"]>

export type CurriculumSelectScalar = {
  id?: boolean
  userId?: boolean
  url?: boolean
  createdAt?: boolean
}

export type CurriculumOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "url" | "createdAt", ExtArgs["result"]["curriculum"]>
export type CurriculumInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CurriculumIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CurriculumIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CurriculumPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Curriculum"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    url: string
    createdAt: Date
  }, ExtArgs["result"]["curriculum"]>
  composites: {}
}

export type CurriculumGetPayload<S extends boolean | null | undefined | CurriculumDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CurriculumPayload, S>

export type CurriculumCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CurriculumFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CurriculumCountAggregateInputType | true
  }

export interface CurriculumDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Curriculum'], meta: { name: 'Curriculum' } }
  /**
   * Find zero or one Curriculum that matches the filter.
   * @param {CurriculumFindUniqueArgs} args - Arguments to find a Curriculum
   * @example
   * // Get one Curriculum
   * const curriculum = await prisma.curriculum.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CurriculumFindUniqueArgs>(args: Prisma.SelectSubset<T, CurriculumFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Curriculum that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CurriculumFindUniqueOrThrowArgs} args - Arguments to find a Curriculum
   * @example
   * // Get one Curriculum
   * const curriculum = await prisma.curriculum.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CurriculumFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CurriculumFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Curriculum that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumFindFirstArgs} args - Arguments to find a Curriculum
   * @example
   * // Get one Curriculum
   * const curriculum = await prisma.curriculum.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CurriculumFindFirstArgs>(args?: Prisma.SelectSubset<T, CurriculumFindFirstArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Curriculum that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumFindFirstOrThrowArgs} args - Arguments to find a Curriculum
   * @example
   * // Get one Curriculum
   * const curriculum = await prisma.curriculum.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CurriculumFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CurriculumFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Curricula that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Curricula
   * const curricula = await prisma.curriculum.findMany()
   * 
   * // Get first 10 Curricula
   * const curricula = await prisma.curriculum.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const curriculumWithIdOnly = await prisma.curriculum.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CurriculumFindManyArgs>(args?: Prisma.SelectSubset<T, CurriculumFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Curriculum.
   * @param {CurriculumCreateArgs} args - Arguments to create a Curriculum.
   * @example
   * // Create one Curriculum
   * const Curriculum = await prisma.curriculum.create({
   *   data: {
   *     // ... data to create a Curriculum
   *   }
   * })
   * 
   */
  create<T extends CurriculumCreateArgs>(args: Prisma.SelectSubset<T, CurriculumCreateArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Curricula.
   * @param {CurriculumCreateManyArgs} args - Arguments to create many Curricula.
   * @example
   * // Create many Curricula
   * const curriculum = await prisma.curriculum.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CurriculumCreateManyArgs>(args?: Prisma.SelectSubset<T, CurriculumCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Curricula and returns the data saved in the database.
   * @param {CurriculumCreateManyAndReturnArgs} args - Arguments to create many Curricula.
   * @example
   * // Create many Curricula
   * const curriculum = await prisma.curriculum.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Curricula and only return the `id`
   * const curriculumWithIdOnly = await prisma.curriculum.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CurriculumCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CurriculumCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Curriculum.
   * @param {CurriculumDeleteArgs} args - Arguments to delete one Curriculum.
   * @example
   * // Delete one Curriculum
   * const Curriculum = await prisma.curriculum.delete({
   *   where: {
   *     // ... filter to delete one Curriculum
   *   }
   * })
   * 
   */
  delete<T extends CurriculumDeleteArgs>(args: Prisma.SelectSubset<T, CurriculumDeleteArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Curriculum.
   * @param {CurriculumUpdateArgs} args - Arguments to update one Curriculum.
   * @example
   * // Update one Curriculum
   * const curriculum = await prisma.curriculum.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CurriculumUpdateArgs>(args: Prisma.SelectSubset<T, CurriculumUpdateArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Curricula.
   * @param {CurriculumDeleteManyArgs} args - Arguments to filter Curricula to delete.
   * @example
   * // Delete a few Curricula
   * const { count } = await prisma.curriculum.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CurriculumDeleteManyArgs>(args?: Prisma.SelectSubset<T, CurriculumDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Curricula.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Curricula
   * const curriculum = await prisma.curriculum.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CurriculumUpdateManyArgs>(args: Prisma.SelectSubset<T, CurriculumUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Curricula and returns the data updated in the database.
   * @param {CurriculumUpdateManyAndReturnArgs} args - Arguments to update many Curricula.
   * @example
   * // Update many Curricula
   * const curriculum = await prisma.curriculum.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Curricula and only return the `id`
   * const curriculumWithIdOnly = await prisma.curriculum.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CurriculumUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CurriculumUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Curriculum.
   * @param {CurriculumUpsertArgs} args - Arguments to update or create a Curriculum.
   * @example
   * // Update or create a Curriculum
   * const curriculum = await prisma.curriculum.upsert({
   *   create: {
   *     // ... data to create a Curriculum
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Curriculum we want to update
   *   }
   * })
   */
  upsert<T extends CurriculumUpsertArgs>(args: Prisma.SelectSubset<T, CurriculumUpsertArgs<ExtArgs>>): Prisma.Prisma__CurriculumClient<runtime.Types.Result.GetResult<Prisma.$CurriculumPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Curricula.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumCountArgs} args - Arguments to filter Curricula to count.
   * @example
   * // Count the number of Curricula
   * const count = await prisma.curriculum.count({
   *   where: {
   *     // ... the filter for the Curricula we want to count
   *   }
   * })
  **/
  count<T extends CurriculumCountArgs>(
    args?: Prisma.Subset<T, CurriculumCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CurriculumCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Curriculum.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CurriculumAggregateArgs>(args: Prisma.Subset<T, CurriculumAggregateArgs>): Prisma.PrismaPromise<GetCurriculumAggregateType<T>>

  /**
   * Group by Curriculum.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurriculumGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CurriculumGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CurriculumGroupByArgs['orderBy'] }
      : { orderBy?: CurriculumGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CurriculumGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCurriculumGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Curriculum model
 */
readonly fields: CurriculumFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Curriculum.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CurriculumClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Curriculum model
 */
export interface CurriculumFieldRefs {
  readonly id: Prisma.FieldRef<"Curriculum", 'Int'>
  readonly userId: Prisma.FieldRef<"Curriculum", 'Int'>
  readonly url: Prisma.FieldRef<"Curriculum", 'String'>
  readonly createdAt: Prisma.FieldRef<"Curriculum", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Curriculum findUnique
 */
export type CurriculumFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * Filter, which Curriculum to fetch.
   */
  where: Prisma.CurriculumWhereUniqueInput
}

/**
 * Curriculum findUniqueOrThrow
 */
export type CurriculumFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * Filter, which Curriculum to fetch.
   */
  where: Prisma.CurriculumWhereUniqueInput
}

/**
 * Curriculum findFirst
 */
export type CurriculumFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * Filter, which Curriculum to fetch.
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Curricula to fetch.
   */
  orderBy?: Prisma.CurriculumOrderByWithRelationInput | Prisma.CurriculumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Curricula.
   */
  cursor?: Prisma.CurriculumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Curricula from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Curricula.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Curricula.
   */
  distinct?: Prisma.CurriculumScalarFieldEnum | Prisma.CurriculumScalarFieldEnum[]
}

/**
 * Curriculum findFirstOrThrow
 */
export type CurriculumFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * Filter, which Curriculum to fetch.
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Curricula to fetch.
   */
  orderBy?: Prisma.CurriculumOrderByWithRelationInput | Prisma.CurriculumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Curricula.
   */
  cursor?: Prisma.CurriculumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Curricula from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Curricula.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Curricula.
   */
  distinct?: Prisma.CurriculumScalarFieldEnum | Prisma.CurriculumScalarFieldEnum[]
}

/**
 * Curriculum findMany
 */
export type CurriculumFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * Filter, which Curricula to fetch.
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Curricula to fetch.
   */
  orderBy?: Prisma.CurriculumOrderByWithRelationInput | Prisma.CurriculumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Curricula.
   */
  cursor?: Prisma.CurriculumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Curricula from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Curricula.
   */
  skip?: number
  distinct?: Prisma.CurriculumScalarFieldEnum | Prisma.CurriculumScalarFieldEnum[]
}

/**
 * Curriculum create
 */
export type CurriculumCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * The data needed to create a Curriculum.
   */
  data: Prisma.XOR<Prisma.CurriculumCreateInput, Prisma.CurriculumUncheckedCreateInput>
}

/**
 * Curriculum createMany
 */
export type CurriculumCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Curricula.
   */
  data: Prisma.CurriculumCreateManyInput | Prisma.CurriculumCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Curriculum createManyAndReturn
 */
export type CurriculumCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * The data used to create many Curricula.
   */
  data: Prisma.CurriculumCreateManyInput | Prisma.CurriculumCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Curriculum update
 */
export type CurriculumUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * The data needed to update a Curriculum.
   */
  data: Prisma.XOR<Prisma.CurriculumUpdateInput, Prisma.CurriculumUncheckedUpdateInput>
  /**
   * Choose, which Curriculum to update.
   */
  where: Prisma.CurriculumWhereUniqueInput
}

/**
 * Curriculum updateMany
 */
export type CurriculumUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Curricula.
   */
  data: Prisma.XOR<Prisma.CurriculumUpdateManyMutationInput, Prisma.CurriculumUncheckedUpdateManyInput>
  /**
   * Filter which Curricula to update
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * Limit how many Curricula to update.
   */
  limit?: number
}

/**
 * Curriculum updateManyAndReturn
 */
export type CurriculumUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * The data used to update Curricula.
   */
  data: Prisma.XOR<Prisma.CurriculumUpdateManyMutationInput, Prisma.CurriculumUncheckedUpdateManyInput>
  /**
   * Filter which Curricula to update
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * Limit how many Curricula to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Curriculum upsert
 */
export type CurriculumUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * The filter to search for the Curriculum to update in case it exists.
   */
  where: Prisma.CurriculumWhereUniqueInput
  /**
   * In case the Curriculum found by the `where` argument doesn't exist, create a new Curriculum with this data.
   */
  create: Prisma.XOR<Prisma.CurriculumCreateInput, Prisma.CurriculumUncheckedCreateInput>
  /**
   * In case the Curriculum was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CurriculumUpdateInput, Prisma.CurriculumUncheckedUpdateInput>
}

/**
 * Curriculum delete
 */
export type CurriculumDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
  /**
   * Filter which Curriculum to delete.
   */
  where: Prisma.CurriculumWhereUniqueInput
}

/**
 * Curriculum deleteMany
 */
export type CurriculumDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Curricula to delete
   */
  where?: Prisma.CurriculumWhereInput
  /**
   * Limit how many Curricula to delete.
   */
  limit?: number
}

/**
 * Curriculum without action
 */
export type CurriculumDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Curriculum
   */
  select?: Prisma.CurriculumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Curriculum
   */
  omit?: Prisma.CurriculumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CurriculumInclude<ExtArgs> | null
}
