
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InfoLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InfoLink
 * 
 */
export type InfoLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$InfoLinkPayload>

export type AggregateInfoLink = {
  _count: InfoLinkCountAggregateOutputType | null
  _avg: InfoLinkAvgAggregateOutputType | null
  _sum: InfoLinkSumAggregateOutputType | null
  _min: InfoLinkMinAggregateOutputType | null
  _max: InfoLinkMaxAggregateOutputType | null
}

export type InfoLinkAvgAggregateOutputType = {
  id: number | null
  infoId: number | null
}

export type InfoLinkSumAggregateOutputType = {
  id: number | null
  infoId: number | null
}

export type InfoLinkMinAggregateOutputType = {
  id: number | null
  infoId: number | null
  title: string | null
  link: string | null
  createdAt: Date | null
}

export type InfoLinkMaxAggregateOutputType = {
  id: number | null
  infoId: number | null
  title: string | null
  link: string | null
  createdAt: Date | null
}

export type InfoLinkCountAggregateOutputType = {
  id: number
  infoId: number
  title: number
  link: number
  createdAt: number
  _all: number
}


export type InfoLinkAvgAggregateInputType = {
  id?: true
  infoId?: true
}

export type InfoLinkSumAggregateInputType = {
  id?: true
  infoId?: true
}

export type InfoLinkMinAggregateInputType = {
  id?: true
  infoId?: true
  title?: true
  link?: true
  createdAt?: true
}

export type InfoLinkMaxAggregateInputType = {
  id?: true
  infoId?: true
  title?: true
  link?: true
  createdAt?: true
}

export type InfoLinkCountAggregateInputType = {
  id?: true
  infoId?: true
  title?: true
  link?: true
  createdAt?: true
  _all?: true
}

export type InfoLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InfoLink to aggregate.
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InfoLinks to fetch.
   */
  orderBy?: Prisma.InfoLinkOrderByWithRelationInput | Prisma.InfoLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InfoLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InfoLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InfoLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InfoLinks
  **/
  _count?: true | InfoLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InfoLinkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InfoLinkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InfoLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InfoLinkMaxAggregateInputType
}

export type GetInfoLinkAggregateType<T extends InfoLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateInfoLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInfoLink[P]>
    : Prisma.GetScalarType<T[P], AggregateInfoLink[P]>
}




export type InfoLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InfoLinkWhereInput
  orderBy?: Prisma.InfoLinkOrderByWithAggregationInput | Prisma.InfoLinkOrderByWithAggregationInput[]
  by: Prisma.InfoLinkScalarFieldEnum[] | Prisma.InfoLinkScalarFieldEnum
  having?: Prisma.InfoLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InfoLinkCountAggregateInputType | true
  _avg?: InfoLinkAvgAggregateInputType
  _sum?: InfoLinkSumAggregateInputType
  _min?: InfoLinkMinAggregateInputType
  _max?: InfoLinkMaxAggregateInputType
}

export type InfoLinkGroupByOutputType = {
  id: number
  infoId: number
  title: string
  link: string
  createdAt: Date
  _count: InfoLinkCountAggregateOutputType | null
  _avg: InfoLinkAvgAggregateOutputType | null
  _sum: InfoLinkSumAggregateOutputType | null
  _min: InfoLinkMinAggregateOutputType | null
  _max: InfoLinkMaxAggregateOutputType | null
}

type GetInfoLinkGroupByPayload<T extends InfoLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InfoLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InfoLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InfoLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InfoLinkGroupByOutputType[P]>
      }
    >
  >



export type InfoLinkWhereInput = {
  AND?: Prisma.InfoLinkWhereInput | Prisma.InfoLinkWhereInput[]
  OR?: Prisma.InfoLinkWhereInput[]
  NOT?: Prisma.InfoLinkWhereInput | Prisma.InfoLinkWhereInput[]
  id?: Prisma.IntFilter<"InfoLink"> | number
  infoId?: Prisma.IntFilter<"InfoLink"> | number
  title?: Prisma.StringFilter<"InfoLink"> | string
  link?: Prisma.StringFilter<"InfoLink"> | string
  createdAt?: Prisma.DateTimeFilter<"InfoLink"> | Date | string
  info?: Prisma.XOR<Prisma.InfoScalarRelationFilter, Prisma.InfoWhereInput>
}

export type InfoLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  link?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  info?: Prisma.InfoOrderByWithRelationInput
}

export type InfoLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.InfoLinkWhereInput | Prisma.InfoLinkWhereInput[]
  OR?: Prisma.InfoLinkWhereInput[]
  NOT?: Prisma.InfoLinkWhereInput | Prisma.InfoLinkWhereInput[]
  infoId?: Prisma.IntFilter<"InfoLink"> | number
  title?: Prisma.StringFilter<"InfoLink"> | string
  link?: Prisma.StringFilter<"InfoLink"> | string
  createdAt?: Prisma.DateTimeFilter<"InfoLink"> | Date | string
  info?: Prisma.XOR<Prisma.InfoScalarRelationFilter, Prisma.InfoWhereInput>
}, "id">

export type InfoLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  link?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.InfoLinkCountOrderByAggregateInput
  _avg?: Prisma.InfoLinkAvgOrderByAggregateInput
  _max?: Prisma.InfoLinkMaxOrderByAggregateInput
  _min?: Prisma.InfoLinkMinOrderByAggregateInput
  _sum?: Prisma.InfoLinkSumOrderByAggregateInput
}

export type InfoLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.InfoLinkScalarWhereWithAggregatesInput | Prisma.InfoLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.InfoLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InfoLinkScalarWhereWithAggregatesInput | Prisma.InfoLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"InfoLink"> | number
  infoId?: Prisma.IntWithAggregatesFilter<"InfoLink"> | number
  title?: Prisma.StringWithAggregatesFilter<"InfoLink"> | string
  link?: Prisma.StringWithAggregatesFilter<"InfoLink"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InfoLink"> | Date | string
}

export type InfoLinkCreateInput = {
  title: string
  link: string
  createdAt?: Date | string
  info: Prisma.InfoCreateNestedOneWithoutLinksInput
}

export type InfoLinkUncheckedCreateInput = {
  id?: number
  infoId: number
  title: string
  link: string
  createdAt?: Date | string
}

export type InfoLinkUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  info?: Prisma.InfoUpdateOneRequiredWithoutLinksNestedInput
}

export type InfoLinkUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  infoId?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InfoLinkCreateManyInput = {
  id?: number
  infoId: number
  title: string
  link: string
  createdAt?: Date | string
}

export type InfoLinkUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InfoLinkUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  infoId?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InfoLinkListRelationFilter = {
  every?: Prisma.InfoLinkWhereInput
  some?: Prisma.InfoLinkWhereInput
  none?: Prisma.InfoLinkWhereInput
}

export type InfoLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InfoLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  link?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InfoLinkAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
}

export type InfoLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  link?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InfoLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  link?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InfoLinkSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  infoId?: Prisma.SortOrder
}

export type InfoLinkCreateNestedManyWithoutInfoInput = {
  create?: Prisma.XOR<Prisma.InfoLinkCreateWithoutInfoInput, Prisma.InfoLinkUncheckedCreateWithoutInfoInput> | Prisma.InfoLinkCreateWithoutInfoInput[] | Prisma.InfoLinkUncheckedCreateWithoutInfoInput[]
  connectOrCreate?: Prisma.InfoLinkCreateOrConnectWithoutInfoInput | Prisma.InfoLinkCreateOrConnectWithoutInfoInput[]
  createMany?: Prisma.InfoLinkCreateManyInfoInputEnvelope
  connect?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
}

export type InfoLinkUncheckedCreateNestedManyWithoutInfoInput = {
  create?: Prisma.XOR<Prisma.InfoLinkCreateWithoutInfoInput, Prisma.InfoLinkUncheckedCreateWithoutInfoInput> | Prisma.InfoLinkCreateWithoutInfoInput[] | Prisma.InfoLinkUncheckedCreateWithoutInfoInput[]
  connectOrCreate?: Prisma.InfoLinkCreateOrConnectWithoutInfoInput | Prisma.InfoLinkCreateOrConnectWithoutInfoInput[]
  createMany?: Prisma.InfoLinkCreateManyInfoInputEnvelope
  connect?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
}

export type InfoLinkUpdateManyWithoutInfoNestedInput = {
  create?: Prisma.XOR<Prisma.InfoLinkCreateWithoutInfoInput, Prisma.InfoLinkUncheckedCreateWithoutInfoInput> | Prisma.InfoLinkCreateWithoutInfoInput[] | Prisma.InfoLinkUncheckedCreateWithoutInfoInput[]
  connectOrCreate?: Prisma.InfoLinkCreateOrConnectWithoutInfoInput | Prisma.InfoLinkCreateOrConnectWithoutInfoInput[]
  upsert?: Prisma.InfoLinkUpsertWithWhereUniqueWithoutInfoInput | Prisma.InfoLinkUpsertWithWhereUniqueWithoutInfoInput[]
  createMany?: Prisma.InfoLinkCreateManyInfoInputEnvelope
  set?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  disconnect?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  delete?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  connect?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  update?: Prisma.InfoLinkUpdateWithWhereUniqueWithoutInfoInput | Prisma.InfoLinkUpdateWithWhereUniqueWithoutInfoInput[]
  updateMany?: Prisma.InfoLinkUpdateManyWithWhereWithoutInfoInput | Prisma.InfoLinkUpdateManyWithWhereWithoutInfoInput[]
  deleteMany?: Prisma.InfoLinkScalarWhereInput | Prisma.InfoLinkScalarWhereInput[]
}

export type InfoLinkUncheckedUpdateManyWithoutInfoNestedInput = {
  create?: Prisma.XOR<Prisma.InfoLinkCreateWithoutInfoInput, Prisma.InfoLinkUncheckedCreateWithoutInfoInput> | Prisma.InfoLinkCreateWithoutInfoInput[] | Prisma.InfoLinkUncheckedCreateWithoutInfoInput[]
  connectOrCreate?: Prisma.InfoLinkCreateOrConnectWithoutInfoInput | Prisma.InfoLinkCreateOrConnectWithoutInfoInput[]
  upsert?: Prisma.InfoLinkUpsertWithWhereUniqueWithoutInfoInput | Prisma.InfoLinkUpsertWithWhereUniqueWithoutInfoInput[]
  createMany?: Prisma.InfoLinkCreateManyInfoInputEnvelope
  set?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  disconnect?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  delete?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  connect?: Prisma.InfoLinkWhereUniqueInput | Prisma.InfoLinkWhereUniqueInput[]
  update?: Prisma.InfoLinkUpdateWithWhereUniqueWithoutInfoInput | Prisma.InfoLinkUpdateWithWhereUniqueWithoutInfoInput[]
  updateMany?: Prisma.InfoLinkUpdateManyWithWhereWithoutInfoInput | Prisma.InfoLinkUpdateManyWithWhereWithoutInfoInput[]
  deleteMany?: Prisma.InfoLinkScalarWhereInput | Prisma.InfoLinkScalarWhereInput[]
}

export type InfoLinkCreateWithoutInfoInput = {
  title: string
  link: string
  createdAt?: Date | string
}

export type InfoLinkUncheckedCreateWithoutInfoInput = {
  id?: number
  title: string
  link: string
  createdAt?: Date | string
}

export type InfoLinkCreateOrConnectWithoutInfoInput = {
  where: Prisma.InfoLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.InfoLinkCreateWithoutInfoInput, Prisma.InfoLinkUncheckedCreateWithoutInfoInput>
}

export type InfoLinkCreateManyInfoInputEnvelope = {
  data: Prisma.InfoLinkCreateManyInfoInput | Prisma.InfoLinkCreateManyInfoInput[]
  skipDuplicates?: boolean
}

export type InfoLinkUpsertWithWhereUniqueWithoutInfoInput = {
  where: Prisma.InfoLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.InfoLinkUpdateWithoutInfoInput, Prisma.InfoLinkUncheckedUpdateWithoutInfoInput>
  create: Prisma.XOR<Prisma.InfoLinkCreateWithoutInfoInput, Prisma.InfoLinkUncheckedCreateWithoutInfoInput>
}

export type InfoLinkUpdateWithWhereUniqueWithoutInfoInput = {
  where: Prisma.InfoLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.InfoLinkUpdateWithoutInfoInput, Prisma.InfoLinkUncheckedUpdateWithoutInfoInput>
}

export type InfoLinkUpdateManyWithWhereWithoutInfoInput = {
  where: Prisma.InfoLinkScalarWhereInput
  data: Prisma.XOR<Prisma.InfoLinkUpdateManyMutationInput, Prisma.InfoLinkUncheckedUpdateManyWithoutInfoInput>
}

export type InfoLinkScalarWhereInput = {
  AND?: Prisma.InfoLinkScalarWhereInput | Prisma.InfoLinkScalarWhereInput[]
  OR?: Prisma.InfoLinkScalarWhereInput[]
  NOT?: Prisma.InfoLinkScalarWhereInput | Prisma.InfoLinkScalarWhereInput[]
  id?: Prisma.IntFilter<"InfoLink"> | number
  infoId?: Prisma.IntFilter<"InfoLink"> | number
  title?: Prisma.StringFilter<"InfoLink"> | string
  link?: Prisma.StringFilter<"InfoLink"> | string
  createdAt?: Prisma.DateTimeFilter<"InfoLink"> | Date | string
}

export type InfoLinkCreateManyInfoInput = {
  id?: number
  title: string
  link: string
  createdAt?: Date | string
}

export type InfoLinkUpdateWithoutInfoInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InfoLinkUncheckedUpdateWithoutInfoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InfoLinkUncheckedUpdateManyWithoutInfoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InfoLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  infoId?: boolean
  title?: boolean
  link?: boolean
  createdAt?: boolean
  info?: boolean | Prisma.InfoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["infoLink"]>

export type InfoLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  infoId?: boolean
  title?: boolean
  link?: boolean
  createdAt?: boolean
  info?: boolean | Prisma.InfoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["infoLink"]>

export type InfoLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  infoId?: boolean
  title?: boolean
  link?: boolean
  createdAt?: boolean
  info?: boolean | Prisma.InfoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["infoLink"]>

export type InfoLinkSelectScalar = {
  id?: boolean
  infoId?: boolean
  title?: boolean
  link?: boolean
  createdAt?: boolean
}

export type InfoLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "infoId" | "title" | "link" | "createdAt", ExtArgs["result"]["infoLink"]>
export type InfoLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  info?: boolean | Prisma.InfoDefaultArgs<ExtArgs>
}
export type InfoLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  info?: boolean | Prisma.InfoDefaultArgs<ExtArgs>
}
export type InfoLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  info?: boolean | Prisma.InfoDefaultArgs<ExtArgs>
}

export type $InfoLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InfoLink"
  objects: {
    info: Prisma.$InfoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    infoId: number
    title: string
    link: string
    createdAt: Date
  }, ExtArgs["result"]["infoLink"]>
  composites: {}
}

export type InfoLinkGetPayload<S extends boolean | null | undefined | InfoLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload, S>

export type InfoLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InfoLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InfoLinkCountAggregateInputType | true
  }

export interface InfoLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InfoLink'], meta: { name: 'InfoLink' } }
  /**
   * Find zero or one InfoLink that matches the filter.
   * @param {InfoLinkFindUniqueArgs} args - Arguments to find a InfoLink
   * @example
   * // Get one InfoLink
   * const infoLink = await prisma.infoLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InfoLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, InfoLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InfoLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InfoLinkFindUniqueOrThrowArgs} args - Arguments to find a InfoLink
   * @example
   * // Get one InfoLink
   * const infoLink = await prisma.infoLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InfoLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InfoLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InfoLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkFindFirstArgs} args - Arguments to find a InfoLink
   * @example
   * // Get one InfoLink
   * const infoLink = await prisma.infoLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InfoLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, InfoLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InfoLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkFindFirstOrThrowArgs} args - Arguments to find a InfoLink
   * @example
   * // Get one InfoLink
   * const infoLink = await prisma.infoLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InfoLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InfoLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InfoLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InfoLinks
   * const infoLinks = await prisma.infoLink.findMany()
   * 
   * // Get first 10 InfoLinks
   * const infoLinks = await prisma.infoLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const infoLinkWithIdOnly = await prisma.infoLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InfoLinkFindManyArgs>(args?: Prisma.SelectSubset<T, InfoLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InfoLink.
   * @param {InfoLinkCreateArgs} args - Arguments to create a InfoLink.
   * @example
   * // Create one InfoLink
   * const InfoLink = await prisma.infoLink.create({
   *   data: {
   *     // ... data to create a InfoLink
   *   }
   * })
   * 
   */
  create<T extends InfoLinkCreateArgs>(args: Prisma.SelectSubset<T, InfoLinkCreateArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InfoLinks.
   * @param {InfoLinkCreateManyArgs} args - Arguments to create many InfoLinks.
   * @example
   * // Create many InfoLinks
   * const infoLink = await prisma.infoLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InfoLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, InfoLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InfoLinks and returns the data saved in the database.
   * @param {InfoLinkCreateManyAndReturnArgs} args - Arguments to create many InfoLinks.
   * @example
   * // Create many InfoLinks
   * const infoLink = await prisma.infoLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InfoLinks and only return the `id`
   * const infoLinkWithIdOnly = await prisma.infoLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InfoLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InfoLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InfoLink.
   * @param {InfoLinkDeleteArgs} args - Arguments to delete one InfoLink.
   * @example
   * // Delete one InfoLink
   * const InfoLink = await prisma.infoLink.delete({
   *   where: {
   *     // ... filter to delete one InfoLink
   *   }
   * })
   * 
   */
  delete<T extends InfoLinkDeleteArgs>(args: Prisma.SelectSubset<T, InfoLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InfoLink.
   * @param {InfoLinkUpdateArgs} args - Arguments to update one InfoLink.
   * @example
   * // Update one InfoLink
   * const infoLink = await prisma.infoLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InfoLinkUpdateArgs>(args: Prisma.SelectSubset<T, InfoLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InfoLinks.
   * @param {InfoLinkDeleteManyArgs} args - Arguments to filter InfoLinks to delete.
   * @example
   * // Delete a few InfoLinks
   * const { count } = await prisma.infoLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InfoLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, InfoLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InfoLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InfoLinks
   * const infoLink = await prisma.infoLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InfoLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, InfoLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InfoLinks and returns the data updated in the database.
   * @param {InfoLinkUpdateManyAndReturnArgs} args - Arguments to update many InfoLinks.
   * @example
   * // Update many InfoLinks
   * const infoLink = await prisma.infoLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InfoLinks and only return the `id`
   * const infoLinkWithIdOnly = await prisma.infoLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InfoLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InfoLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InfoLink.
   * @param {InfoLinkUpsertArgs} args - Arguments to update or create a InfoLink.
   * @example
   * // Update or create a InfoLink
   * const infoLink = await prisma.infoLink.upsert({
   *   create: {
   *     // ... data to create a InfoLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InfoLink we want to update
   *   }
   * })
   */
  upsert<T extends InfoLinkUpsertArgs>(args: Prisma.SelectSubset<T, InfoLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__InfoLinkClient<runtime.Types.Result.GetResult<Prisma.$InfoLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InfoLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkCountArgs} args - Arguments to filter InfoLinks to count.
   * @example
   * // Count the number of InfoLinks
   * const count = await prisma.infoLink.count({
   *   where: {
   *     // ... the filter for the InfoLinks we want to count
   *   }
   * })
  **/
  count<T extends InfoLinkCountArgs>(
    args?: Prisma.Subset<T, InfoLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InfoLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InfoLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InfoLinkAggregateArgs>(args: Prisma.Subset<T, InfoLinkAggregateArgs>): Prisma.PrismaPromise<GetInfoLinkAggregateType<T>>

  /**
   * Group by InfoLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InfoLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InfoLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InfoLinkGroupByArgs['orderBy'] }
      : { orderBy?: InfoLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InfoLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInfoLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InfoLink model
 */
readonly fields: InfoLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InfoLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InfoLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  info<T extends Prisma.InfoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.InfoDefaultArgs<ExtArgs>>): Prisma.Prisma__InfoClient<runtime.Types.Result.GetResult<Prisma.$InfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InfoLink model
 */
export interface InfoLinkFieldRefs {
  readonly id: Prisma.FieldRef<"InfoLink", 'Int'>
  readonly infoId: Prisma.FieldRef<"InfoLink", 'Int'>
  readonly title: Prisma.FieldRef<"InfoLink", 'String'>
  readonly link: Prisma.FieldRef<"InfoLink", 'String'>
  readonly createdAt: Prisma.FieldRef<"InfoLink", 'DateTime'>
}
    

// Custom InputTypes
/**
 * InfoLink findUnique
 */
export type InfoLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * Filter, which InfoLink to fetch.
   */
  where: Prisma.InfoLinkWhereUniqueInput
}

/**
 * InfoLink findUniqueOrThrow
 */
export type InfoLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * Filter, which InfoLink to fetch.
   */
  where: Prisma.InfoLinkWhereUniqueInput
}

/**
 * InfoLink findFirst
 */
export type InfoLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * Filter, which InfoLink to fetch.
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InfoLinks to fetch.
   */
  orderBy?: Prisma.InfoLinkOrderByWithRelationInput | Prisma.InfoLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InfoLinks.
   */
  cursor?: Prisma.InfoLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InfoLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InfoLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InfoLinks.
   */
  distinct?: Prisma.InfoLinkScalarFieldEnum | Prisma.InfoLinkScalarFieldEnum[]
}

/**
 * InfoLink findFirstOrThrow
 */
export type InfoLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * Filter, which InfoLink to fetch.
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InfoLinks to fetch.
   */
  orderBy?: Prisma.InfoLinkOrderByWithRelationInput | Prisma.InfoLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InfoLinks.
   */
  cursor?: Prisma.InfoLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InfoLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InfoLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InfoLinks.
   */
  distinct?: Prisma.InfoLinkScalarFieldEnum | Prisma.InfoLinkScalarFieldEnum[]
}

/**
 * InfoLink findMany
 */
export type InfoLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * Filter, which InfoLinks to fetch.
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InfoLinks to fetch.
   */
  orderBy?: Prisma.InfoLinkOrderByWithRelationInput | Prisma.InfoLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InfoLinks.
   */
  cursor?: Prisma.InfoLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InfoLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InfoLinks.
   */
  skip?: number
  distinct?: Prisma.InfoLinkScalarFieldEnum | Prisma.InfoLinkScalarFieldEnum[]
}

/**
 * InfoLink create
 */
export type InfoLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a InfoLink.
   */
  data: Prisma.XOR<Prisma.InfoLinkCreateInput, Prisma.InfoLinkUncheckedCreateInput>
}

/**
 * InfoLink createMany
 */
export type InfoLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InfoLinks.
   */
  data: Prisma.InfoLinkCreateManyInput | Prisma.InfoLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InfoLink createManyAndReturn
 */
export type InfoLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * The data used to create many InfoLinks.
   */
  data: Prisma.InfoLinkCreateManyInput | Prisma.InfoLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InfoLink update
 */
export type InfoLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a InfoLink.
   */
  data: Prisma.XOR<Prisma.InfoLinkUpdateInput, Prisma.InfoLinkUncheckedUpdateInput>
  /**
   * Choose, which InfoLink to update.
   */
  where: Prisma.InfoLinkWhereUniqueInput
}

/**
 * InfoLink updateMany
 */
export type InfoLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InfoLinks.
   */
  data: Prisma.XOR<Prisma.InfoLinkUpdateManyMutationInput, Prisma.InfoLinkUncheckedUpdateManyInput>
  /**
   * Filter which InfoLinks to update
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * Limit how many InfoLinks to update.
   */
  limit?: number
}

/**
 * InfoLink updateManyAndReturn
 */
export type InfoLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * The data used to update InfoLinks.
   */
  data: Prisma.XOR<Prisma.InfoLinkUpdateManyMutationInput, Prisma.InfoLinkUncheckedUpdateManyInput>
  /**
   * Filter which InfoLinks to update
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * Limit how many InfoLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InfoLink upsert
 */
export type InfoLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the InfoLink to update in case it exists.
   */
  where: Prisma.InfoLinkWhereUniqueInput
  /**
   * In case the InfoLink found by the `where` argument doesn't exist, create a new InfoLink with this data.
   */
  create: Prisma.XOR<Prisma.InfoLinkCreateInput, Prisma.InfoLinkUncheckedCreateInput>
  /**
   * In case the InfoLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InfoLinkUpdateInput, Prisma.InfoLinkUncheckedUpdateInput>
}

/**
 * InfoLink delete
 */
export type InfoLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
  /**
   * Filter which InfoLink to delete.
   */
  where: Prisma.InfoLinkWhereUniqueInput
}

/**
 * InfoLink deleteMany
 */
export type InfoLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InfoLinks to delete
   */
  where?: Prisma.InfoLinkWhereInput
  /**
   * Limit how many InfoLinks to delete.
   */
  limit?: number
}

/**
 * InfoLink without action
 */
export type InfoLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InfoLink
   */
  select?: Prisma.InfoLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InfoLink
   */
  omit?: Prisma.InfoLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InfoLinkInclude<ExtArgs> | null
}
